### ISSUE TITLE
SequencedCollection.getFirst()

### ISSUE THREAD

**Issue by regfaker** [eppleton/frgaal#12]
version: 21.0.0
SequencedCollection.getFirst() seems unsupported:
```java
import java.util.List;

public class GetFirst {

	public static void main(String[] args) {
		System.out.println(List.of("a").getFirst());
	}
}
```
```
java -jar compiler-21.0.0.jar --enable-preview -source 21 -target 17 GetFirst.java
GetFirst.java:6: error: cannot find symbol
		System.out.println(List.of("a").getFirst());
		                               ^
  symbol:   method getFirst()
  location: interface List<String>
1 error
```

Can it be added?

Thank you

btw is there some guideline to contributing?

**Comment by jtulach** [comment]
https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/SequencedCollection.html has been introduced in JDK 21. You are using `--target 17`. You cannot (easily) use `SequencedCollection` when targetting JDK 17. The class isn't available there.

**Comment by regfaker** [comment]
Ah, sorry. Yes, I've misunderstood "retrofit" term here. I've thought there's some transpilation (here getFirst -> get(0)). My bad. Thanks. Closing this.

**Comment by jtulach** [comment]
> misunderstood "retrofit" term here

Correct, Frgaal is just about language syntax.

However transpilation is also possible and we are doing it as part of our [nb-javac project](https://github.com/JaroslavTulach/nb-javac/blob/master/make/langtools/netbeans/nb-javac/src/META-INF/upgrade/nbjavac.hint). However it is not done with **Frgaal**, but with a tool for [Java Declarative Refactorings](https://netbeans.apache.org/front/main/jackpot/). The [nb-javac project](https://github.com/JaroslavTulach/nb-javac/) takes `javac` from the latest JDK and _"transpiles it"_ to run on JDK8.
