### ISSUE TITLE
Problem using source/target 19 with gradle (with a workaround)

### ISSUE THREAD

**Issue by errael** [eppleton/frgaal#7]
With gradle 6.8.3, jdk-11, frgaal 19-RC1 a workaround is needed to use javac-19. Doing
```
sourceCompatibility = '19'
println sourceCompatibility
```
outputs `18`

In order to use 19 the following works
```
compileJava {
    ...
    options.compilerArgs << '-source' << '19'
}

```

**Comment by errael** [comment]
FYI, opened https://github.com/apache/netbeans/issues/4704 since it seems like the NetBeans gradle tooling will not necessarily set the correct jdk version for NetBeans to use.

**Comment by dukescript** [comment]
@errael what action shall be taken to close this issue? Update `README.md`? Do you want to create a PR?

**Comment by errael** [comment]
With PR #11 can close this issue.
